baseURL = "https://xingvec.github.io/"
languageCode = "zh-cn"
title = "Xingvec's Blog"
theme = "stack"

[params]
  mainSection = "posts"
  articleSection = ["posts"]
  toc = true
  tocOpen = false
  readingTime = true

  [params.sidebar]
    subtitle = "欢迎来到我的博客"

    [params.sidebar.avatar]
      enabled = true
      local = true
      src = "img/xingvectx.png"

  [params.article]
    [params.article.readingTime]
      enable = true

  [params.colorScheme]
    toggle = true
    default = "auto"

  [params.widgets]
    [[params.widgets.homepage]]
      type = "search"
    [[params.widgets.homepage]]
      type = "archives"
      [params.widgets.homepage.params]
        limit = 5
    [[params.widgets.homepage]]
      type = "categories"
    [[params.widgets.homepage]]
      type = "tag-cloud"

[[menu.main]]
  name = "首页"
  url = "/"
  weight = 1

[[menu.main]]
  name = "文章"
  url = "/posts/"
  weight = 2

[[menu.main]]
  name = "关于"
  url = "/page/about/"
  weight = 3

[[menu.social]]
  name = "GitHub"
  url = "https://github.com/xingvec"

[markup]
  [markup.highlight]
    style = "monokai"
    lineNos = true
    codeFences = true
    guessSyntax = true
